[package]
name = "keyboard-labs-keyberon"
version = "0.1.0"
authors = ["Richard Goulter <rchard.goulter@gmail.com>", "Guillaume Pinot <texitoi@texitoi.eu>"]
edition = "2018"

[dependencies]
stm32f4xx-hal = { version = "0.10.1", features = ["rt", "stm32f401", "usb_fs"] }
cortex-m = "0.7"
cortex-m-rt = { version = "0.6.15", features = ["device"] }
panic-halt = "0.2.0"
keyberon = { git = "https://github.com/TeXitoi/keyberon", branch = "master" }
cortex-m-rtic = { version = "0.5", default-features = false, features = ["cortex-m-7"] }
generic-array = "0.13"
embedded-hal = "0.2"
usb-device = "0.2.0"
usbd-hid = "0.6.0"
heapless = "0.5"
nb = "1.0.0"
usbd-serial = "0.1.0"

[profile.release]
lto = true
incremental = false
opt-level = "z"
debug = true
